---
sudo: required
services:
  - docker

language: go

before_script:
 - pwd
 - docker login -u $DOCKER_USER -p $DOCKER_PASS

script:
  - make build test

deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: wip-add-arm-support
