---
sudo: required
services:
  - docker

language: go

before_script:
 - pwd

script:
  - make build test

before_deploy:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: master
